### ISSUE TITLE
RPI build fails

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1086]
might be due to http://stackoverflow.com/questions/9753749/arm-compilation-error-vpf-registered-used-by-executable-not-object-file 
not enough flags passed for go-mysql c++ lib???

```
>>> --- >>> Building /home/builder/diladele/qlproxy/contrib/go/armhf/linux/bin/go build -ldflags -X main.buildver 4.3.0.2E83-armhf-linux-debian7 diladele/qlproxy/database
# diladele/qlproxy/database
/usr/bin/ld: error: $WORK/diladele/qlproxy/database/_obj/exe/a.out uses VFP register arguments, /var/tmp/go-link-DbS81m/000002.o does not
/usr/bin/ld: failed to merge target specific data of file /var/tmp/go-link-DbS81m/000002.o
collect2: ld returned 1 exit status
/home/builder/diladele/qlproxy/contrib/go/armhf/linux/pkg/tool/linux_arm/5l: running gcc failed: unsuccessful exit status 0x100
Traceback (most recent call last):
  File "build.py", line 347, in <module>
    main()
  File "build.py", line 342, in main
    build_inplace(env(arch, not args.debug), deploy)
  File "build.py", line 238, in build_inplace
    build_go(env)
  File "build.py", line 228, in build_go
    subprocess.check_call(cmd, cwd=dir)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/builder/diladele/qlproxy/contrib/go/armhf/linux/bin/go', 'build', '-ldflags', '-X main.buildver 4.3.0.2E83-armhf-linux-debian7', 'diladele/qlproxy/database']' returned non-zero exit status 2
builder@rpi ~/diladele/qlproxy $
```

**Comment by ra-at-diladele-com** [comment]
```
dpkg: error processing qlproxy-4.3.0.65F5_armhfv7.deb (--install):
 package architecture (armhfv7) does not match system (armhf)
```
