### ISSUE TITLE
Could not purge the database

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1169]
[2016-Feb-21 01:04:00.233] [scheduler] [CRITICAL] Could not purge the database, error: 'exit status 2', result: 'panic: Exiting. Error opening the log file: open /opt/qlproxy/var/log/database.log: permission denied

goroutine 1 [running]:
main.prepareLogging(0xc20803cff0, 0x21, 0xc20802aee0, 0x10, 0xc20802af00, 0x10, 0xc20802af20, 0x10, 0x8df751, 0x5, ...)
	/home/builder/diladele/websafety/src.go/src/diladele/qlproxy/database/main.go:244 +0x119
main.perform(0x0, 0x0)
	/home/builder/diladele/websafety/src.go/src/diladele/qlproxy/database/main.go:106 +0x56d
main.main()
	/home/builder/diladele/websafety/src.go/src/diladele/qlproxy/database/main.go:56 +0x1f
'

**Comment by ra-at-diladele-com** [comment]
May be we need to APPEND and not to OPEN EXISTING
