### ISSUE TITLE
Error switching to MySQL on VA ubuntu 16

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#1448]

**Comment by ra-at-diladele-com** [comment]
```

user@websafety:~/scripts.va$ sudo bash 02_sync.sh
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Warning: Since password will be sent to server in plain text, use ssl connection to ensure password safety.
2016-09-29 16:13:32,366 Database manipulation script is starting...
2016-09-29 16:13:32,367 Current system uses SQLite as monitoring database (flag file /opt/qlproxy/var/console/console/database.mysql does not exist).
2016-09-29 16:13:32,367 Adding flag to switch to MySQL...
2016-09-29 16:13:32,367 Flag added successfully
2016-09-29 16:13:32,376 ERROR:
2016-09-29 16:13:32,377 ERROR: Cannot switch database, error: 255
2016-09-29 16:13:32,377 ERROR:
2016-09-29 16:13:32,377 STDOUT:
2016-09-29 16:13:32,378
2016-09-29 16:13:32,378 STDERR:
2016-09-29 16:13:32,378
Traceback (most recent call last):
  File "/opt/qlproxy/var/console/switch_db.py", line 181, in <module>
    main()
  File "/opt/qlproxy/var/console/switch_db.py", line 171, in main
    perform_action(args.db)
  File "/opt/qlproxy/var/console/switch_db.py", line 141, in perform_action
    return switch_to_mysql()
  File "/opt/qlproxy/var/console/switch_db.py", line 89, in switch_to_mysql
    CommandDatabase().run(args)
  File "/opt/qlproxy/var/console/switch_db.py", line 57, in run
    raise Exception("FAILURE!!!")
Exception: FAILURE!!!
2016-09-29 16:13:32,635 Syncing monitoring settings from /opt/qlproxy/var/db/qlproxy.sqlite to /opt/qlproxy/etc/monitor.json...
2016-09-29 16:13:32,635 Using user 'root', password 'Passw0rd'. If you changed the default password for 'root' user modify it here!!!
2016-09-29 16:13:32,635 Authenticating to the database...
2016-09-29 16:13:32,826 Generating /opt/qlproxy/etc/monitor.json file
2016-09-29 16:13:32,838 Success!!!
user@websafety:~/scripts.va$

```

**Comment by ra-at-diladele-com** [comment]
seems we need to change 127.0.0.1 into 'localhost' in settings.py.
Will it work on CentOS 7 ?

**Comment by ra-at-diladele-com** [comment]
reason - on ubuntu 16 with newer mysql (5.7) if MySQL user is specified as 'root' - it will *always* connect to MySQL unix socket, thus ignoring our settings for TCP. We might need to add new user 'qlproxy' and grant him all  permissions on all the databases.

We cannot grant him permissions on OUR database only because our database.exe DROPS this database and thus effectively destroys all permissions. 

What to do?

**Comment by ra-at-diladele-com** [comment]
for now we will create `qlproxy` user for MySQL. In future may be we will drop mysql completely.

**Comment by ra-at-diladele-com** [comment]
done, need to also do  #1451
