### ISSUE TITLE
wsmgrd exists after reload

### ISSUE THREAD

**Issue by ra-at-diladele-com** [ra-at-diladele-com/qlproxy_external#965]
start wsmgrd - everything is fine
browse - see files are processed correctly
click - Save and Reload from Web UI
wsmgrd is exited.

**Comment by ra-at-diladele-com** [comment]
```
[negroni] Started GET /monitoring/analytics/squid/info
[negroni] Completed 200 OK in 4.410421ms
[negroni] Started GET /monitoring/analytics/squid/active_requests
[negroni] Completed 200 OK in 1.569854ms
[negroni] Started GET /monitoring/analytics/squid/active_requests
[negroni] Completed 200 OK in 2.649433ms
[negroni] Started GET /monitoring/analytics/squid/info
[negroni] Completed 200 OK in 1.869791ms
panic: close of closed channel

goroutine 38 [running]:
diladele/qlproxy/modules/monitoring.run(0xc20800c3c0)
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/modules/monitoring/file_event_source.go:98 +0x12d
created by diladele/qlproxy/modules/monitoring.(*FileEventSource).Start
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/modules/monitoring/file_event_source.go:71 +0x660

goroutine 1 [runnable]:
log.Printf(0x8bc2d0, 0x19, 0x0, 0x0, 0x0)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/log/log.go:275
diladele/qlproxy/modules/monitoring.(*FileEventSource).Start(0xc20800c3c0, 0x0, 0x0)
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/modules/monitoring/file_event_source.go:72 +0x698
diladele/qlproxy/modules/monitoring.(*Controller).Start(0xc20803b620, 0x0, 0x0)
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/modules/monitoring/controller.go:97 +0x151
main.(*Modules).Start(0xc20802b0e0, 0x0, 0x0)
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/wsmgrd/modules.go:61 +0xf0
main.main()
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/wsmgrd/main.go:96 +0xd16

goroutine 5 [syscall]:
os/signal.loop()
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 14 [IO wait]:
net.(*pollDesc).Wait(0xc208011090, 0x72, 0x0, 0x0)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011090, 0x0, 0x0)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208011030, 0x0, 0x7f23f6201ac8, 0xc20817c318)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080340b0, 0x563f7e, 0x0, 0x0)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2080340b0, 0x0, 0x0, 0x0, 0x0)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc208030900, 0x7f23f6204d90, 0xc2080340b0, 0x0, 0x0)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc208030900, 0x0, 0x0)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc2080d45b6, 0x6, 0x7f23f6203b18, 0xc2080a11d0, 0x0, 0x0)
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/http/server.go:1808 +0xba
diladele/qlproxy/modules/service.run_server(0xc20802b0c0)
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/modules/service/server.go:39 +0x1b6
created by diladele/qlproxy/modules/service.(*RestServer).Start
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/modules/service/server.go:30 +0x11b

goroutine 15 [select]:
main.func·001()
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/wsmgrd/signals.go:47 +0x106
created by main.(*Signals).subscribe
	/home/builder/diladele/qlproxy/src.go/src/diladele/qlproxy/wsmgrd/signals.go:55 +0x3bb

goroutine 16 [select]:
net.func·019()
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/dnsclient_unix.go:241 +0x2f4
created by net.loadConfig
	/home/builder/diladele/qlproxy/contrib/go/amd64/linux/src/net/dnsclient_unix.go:269 +0x20c
```

**Comment by ea-at-diladele-com** [comment]
should be fixed, but I'm not sure that SIGHUP functions correctly, because it is not available on windows.
Could you please test? Thank you!

**Comment by ra-at-diladele-com** [comment]
after reload
```
015/09/21 13:57:53 Start listening to rest requests on port ':18888'...
2015/09/21 13:57:53 Error: listen tcp :18888: bind: address already in use
```

**Comment by ea-at-diladele-com** [comment]
should be fixed, please check

**Comment by ra-at-diladele-com** [comment]
Seems to be working correctly now; closing...
